### PR TITLE
Make it possible to call create_object

### PR DESCRIPTION
**Pull request by kazufusa**
1. Fix `SHP::Shapefile.create_object` definition from `shapefile::create_simple_object` to `shapefile::create_object`
1. Fix `shapefile::create_object` to make it work
1. Add test

### CODE REVIEW

**Comment by kazufusa** [comment]
my CI result

https://travis-ci.org/kazufusa/shp-ruby

**Comment by zhm** [comment]
This is great. Thank you!

**Comment by zhm** [comment]
0.1.0 is live with your patch. Thanks again!

**Comment by kazufusa** [comment]
You're welcome!

**Pull request merged**
